### PR TITLE
fix: make sure that structs are serialized correctly

### LINKED ISSUE #31: non-canonical encoding
Hey there. I've been using the ipld/dag-cbor library to encode my data.

I just tried using this crate to encode the same data and noticed that it encodes it in the order the struct is declared in.

Here's a test you can run:
```rs
#[test]
  fn test_canonical(){
    use serde::{Serialize, Deserialize};
    #[derive(Serialize, Deserialize, PartialEq, Debug)]
    struct First {
      a: u32,
      b: u32,
    }
    #[derive(Serialize, Deserialize, PartialEq, Debug)]
    struct Second {
      b: u32,
      a: u32,
    }

    let first = First { a: 1, b: 2 };
    let second = Second { a: 1, b: 2 };

    let first_bytes = DagCborCodec::encode_to_vec(&first).unwrap();
    let second_bytes = DagCborCodec::encode_to_vec(&second).unwrap();

    assert_eq!(first_bytes, second_bytes);

  }
```

it fails with:

```
assertion `left == right` failed
  left: [162, 97, 97, 1, 97, 98, 2]
 right: [162, 97, 98, 2, 97, 97, 1]
```

### PR DESCRIPTION
**Pull request by vmx**
Rust structs have their entries ordered the same way as they are defined. When serialized to CBOR, they become maps by default. In
 DAG-CBOR the maps need to have a specific order, hence the keys
might need to be re-ordered, so that they are independent of the order they were defined. This commit makes sure that it's actually the case.

Fixes #31.

### CODE REVIEW

File: src/ser.rs [hunk 1]
```diff
@@ -429,14 +429,50 @@ pub struct CollectMap<'a, W> {
...
+
+        Ok(())
+    }
+
+    fn end(mut self) -> Result<(), EncodeError<W::Error>> {
+        // This sorting step makes sure we have the expected order of the keys. Byte-wise
+        // comparison gives us the right order as keys in DAG-CBOR are always (text) strings, hence
+        // have the same CBOR major type 3. The length of the string is encoded in the following
+        // bits. This means that a shorter string sorts before a longer string.
+        self.entries.sort_unstable();
```
Comment (rvagg) [inline src/ser.rs:470]: I don't think this is enough. We're stuck with the 7049 rules of length-first sorting. https://ipld.io/specs/codecs/dag-cbor/spec/#strictness

A good extension to your tests would be to add a new field to the struct "a1" which should come after "b".

File: src/ser.rs [hunk 2]
```diff
@@ -65,8 +65,8 @@ impl<'a, W: enc::Write> serde::Serializer for &'a mut Serializer<W> {
     type SerializeTupleStruct = BoundedCollect<'a, W>;
     type SerializeTupleVariant = BoundedCollect<'a, W>;
     type SerializeMap = CollectMap<'a, W>;
-    type SerializeStruct = BoundedCollect<'a, W>;
-    type SerializeStructVariant = BoundedCollect<'a, W>;
+    type SerializeStruct = CollectMap<'a, W>;
```
Comment (rvagg) [inline src/ser.rs:68]: Can you educate me on BoundedCollet vs CollectMap?

File: src/ser.rs (hunk 1 above)
Comment (vmx) [reply src/ser.rs:470]: Thanks for pointing out and proposing better tests. Though I think it'ss correct. In a previous PR Steb asked me to clarify this a bit in a comment, but it still doesn't seem to be clear. When you've an idea to word it in a better way, please let me know.

As CBOR prefixes the strings with the length, shorter strings are sorted first. I even think this is the reason they came up with this (counter-intuitive) ordering. So that you can take the full encoded value (not just the string itself) and memcmp it for sorting.

File: src/ser.rs (hunk 2 above)
Comment (vmx) [reply src/ser.rs:68]: The names might not be great, but the idea now is that `BoundedCollect` does take the input in the same order as it comes in without further checks, the `CollectMap` does the whole sorting thing.

Those structs then implement specific traits so that they can be used with those type definitions.

File: src/ser.rs (hunk 1 above)
Comment (Stebalien) [reply src/ser.rs:470]: Importantly, even though the length itself is variable length, the length itself is either:

1. 0-23: inlined into the 5-bit additional data field.
2. 24-27: 1-8 byte length.

Which means that lexicographical sorting actually works.

**Review by Stebalien — APPROVED** [review]

File: src/ser.rs (hunk 1 above)
Comment (rvagg) [reply src/ser.rs:470]: Oh, right, I missed that this was sorting over _encoded_ values; and yeah, neat that it actually works given the flexible prefix!

File: src/ser.rs [hunk 3]
```diff
@@ -429,14 +429,50 @@ pub struct CollectMap<'a, W> {
...
+        self.buffer.clear();
+
+        Ok(())
+    }
+
+    fn end(mut self) -> Result<(), EncodeError<W::Error>> {
+        // This sorting step makes sure we have the expected order of the keys. Byte-wise
+        // comparison gives us the right order as keys in DAG-CBOR are always (text) strings, hence
+        // have the same CBOR major type 3. The length of the string is encoded in the following
+        // bits. This means that a shorter string sorts before a longer string.
```
Comment (rvagg) [inline src/ser.rs:469]:
```suggestion
        // This sorting step makes sure we have the expected order of the keys. Byte-wise
        // comparison over the encoded forms gives us the right order as keys in DAG-CBOR are
        // always (text) strings, hence have the same CBOR major type 3. The length of the string
        // is encoded in the prefix bits along with the major type. This means that a shorter string
        // always sorts before a longer string even with the compact length representation.
```

maybe this? "encoded forms" was the bit I overlooked so I put that in, but also tried to hint toward the mechanism in the second half of the comment
